---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "${ZAP_TARGET_URL}" # Use the variable from GitLab CI
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  # This job adds the Authorization header to every request ZAP makes.
  # It reads the token from the KEYCLOAK_ACCESS_TOKEN environment variable.
  - type: "requester"
    parameters:
      rules:
        - "DELETE http.header.Authorization" # Remove any existing Authorization header
        - "ADD http.header.Authorization Bearer ${KEYCLOAK_ACCESS_TOKEN}" # Add the new one


  - type: "passiveScan-wait" # Passive scan while spidering
    parameters:
      maxDuration: 5 # in minutes

  - type: "spider"
    parameters:
      url: "${ZAP_TARGET_URL}"
      maxDuration: 2

  - type: "report"
    parameters:
      template: "traditional-html"
      reportDir: "wrk" # <-- FIX: Changed from /zap/wrk/ to wrk
      reportFile: "report"
      
  - type: "report"
    parameters:
      template: "traditional-json"
      reportDir: "wrk" # <-- FIX: Changed from /zap/wrk/ to wrk
      reportFile: "gl-dast-report"