---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "${ZAP_TARGET_URL}"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: "passiveScan-wait"
    parameters:
      maxDuration: 5

  - type: "spider"
    parameters:
      url: "${ZAP_TARGET_URL}"
      maxDuration: 2

  - type: "report"
    parameters:
      template: "traditional-html"
      reportDir: "wrk"
      reportFile: "report"
      
  - type: "report"
    parameters:
      template: "traditional-json"
      reportDir: "wrk"
      reportFile: "gl-dast-report"