package company.user_management_service.DTO;

import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LoginResponse {
    private String accessToken;
    private String tokenType;
    private boolean forcePasswordReset;

    // User information
    private String username;
    private String role;

    // Employee details
    private String firstName;
    private String lastName;
    private String phone;
    private String address;
    private String hireDate;
    private Long departmentId;
    private Long managerId;
    private String position;

    public LoginResponse(String token, String bearer, String username, String role, String firstName, String lastName, String phone, String address, String s, Long departmentId, Long managerId, String position) {
        this.accessToken = token;
        this.tokenType = bearer;
        this.username = username;
        this.role = role;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.address = address;
        this.hireDate = s;
        this.departmentId = departmentId;
        this.managerId = managerId;
        this.position = position;
    }

    public static LoginResponseBuilder builder() {
        return new LoginResponseBuilder();
    }

    // Builder class (generated by Lombok, but explicitly defined here for clarity)
    public static class LoginResponseBuilder {
        private String accessToken;
        private String tokenType;
        private boolean forcePasswordReset;
        private String username;
        private String role;
        private String firstName;
        private String lastName;
        private String phone;
        private String address;
        private String hireDate;
        private Long departmentId;
        private Long managerId;
        private String position;

        public LoginResponseBuilder accessToken(String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        public LoginResponseBuilder tokenType(String tokenType) {
            this.tokenType = tokenType;
            return this;
        }

        public LoginResponseBuilder forcePasswordReset(boolean forcePasswordReset) {
            this.forcePasswordReset = forcePasswordReset;
            return this;
        }

        public LoginResponseBuilder username(String username) {
            this.username = username;
            return this;
        }

        public LoginResponseBuilder role(String role) {
            this.role = role;
            return this;
        }

        public LoginResponseBuilder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        public LoginResponseBuilder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        public LoginResponseBuilder phone(String phone) {
            this.phone = phone;
            return this;
        }

        public LoginResponseBuilder address(String address) {
            this.address = address;
            return this;
        }

        public LoginResponseBuilder hireDate(String hireDate) {
            this.hireDate = hireDate;
            return this;
        }

        public LoginResponseBuilder departmentId(Long departmentId) {
            this.departmentId = departmentId;
            return this;
        }

        public LoginResponseBuilder managerId(Long managerId) {
            this.managerId = managerId;
            return this;
        }

        public LoginResponseBuilder position(String position) {
            this.position = position;
            return this;
        }

        public LoginResponse build() {
            return new LoginResponse(accessToken, tokenType, forcePasswordReset,
                    username, role, firstName, lastName,
                    phone, address, hireDate, departmentId,
                    managerId, position);
        }
    }
}