spring.application.name=eureka-server
server.port=${SERVER_PORT:8761}
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false

# Optional Actuator Config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true