# Basic Service Configuration
spring.application.name=user-management-service
server.port=${SERVER_PORT:8085}

# Database Configuration (Docker-friendly)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/management_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Keycloak Configuration (Docker-friendly)
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
keycloak.realm=${KEYCLOAK_REALM:demo}
keycloak.resource=${KEYCLOAK_RESOURCE:demo-rest-api}
keycloak.credentials.secret=${KEYCLOAK_CREDENTIALS_SECRET:3HwnrSXEmvLjpbN9z8qvaaUJ7OqO3U5V}
#keycloak.credentials.secret=${KEYCLOAK_CREDENTIALS_SECRET:eQdOPYR4eVe7KoaMLZvV9RXSNxpIb59a}

# Security Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/demo}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/demo/protocol/openid-connect/certs}

# Eureka Configuration (Docker-friendly)
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.secure-port-enabled=false
eureka.instance.non-secure-port=${server.port}
eureka.instance.statusPageUrl=http://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.healthCheckUrl=http://${eureka.instance.hostname}:${server.port}/actuator/health
eureka.instance.homePageUrl=http://${eureka.instance.hostname}:${server.port}/

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET,POST

# Info Endpoint Configuration
info.app.name=${spring.application.name}
info.app.description=User Management Service
info.app.version=1.0.0