# Basic Service Configuration
spring.application.name=user-management-service
server.port=8085

# Keycloak Configuration (Local)
#keycloak.auth-server-url=http://localhost:8080
# Keycloak Configuration
keycloak.realm=${KEYCLOAK_REALM:Tunisys}
keycloak.auth-server-url=${KEYCLOAK_AUTH_URL:http://keycloak24:8080}
keycloak.resource=${KEYCLOAK_RESOURCE:demo-rest-api}
keycloak.credentials.secret=${KEYCLOAK_CREDENTIALS_SECRET:6ZWEg9yWkbERGGJK0ju0AKaqgTn7S0wI}
keycloak.ssl-required=none
keycloak.bearer-only=true
keycloak.use-resource-role-mappings=true
# Logging
logging.level.org.keycloak=DEBUG
logging.level.org.springframework.security=DEBUG
# Unified Keycloak Configuration (Spring Boot 3+)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak24:8080/realms/Tunisys
spring.security.oauth2.client.registration.keycloak.client-id=demo-rest-api
spring.security.oauth2.client.registration.keycloak.client-secret=6ZWEg9yWkbERGGJK0ju0AKaqgTn7S0wI
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak24:8080/realms/Tunisys

# Eureka Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.hostname=user-management-service
eureka.instance.status-page-url=http://user-management-service:8085/actuator/info
eureka.instance.health-check-url=http://user-management-service:8085/actuator/health
eureka.instance.home-page-url=http://user-management-service:8085/
#eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.application.name}:${server.port}
#eureka.instance.hostname=localhost
#eureka.instance.status-page-url=http://localhost:${server.port}/actuator/info
#eureka.instance.health-check-url=http://localhost:${server.port}/actuator/health
#eureka.instance.home-page-url=http://localhost:${server.port}/

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET,POST

# Info Endpoint Configuration
info.app.name=${spring.application.name}
info.app.description=Department Management Service
info.app.version=1.0.0


#docker run -d --name user-management-service --network my-app-network -p 8085:8085 -e SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http:/
#/keycloak24:8080/realms/Tunisys -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=demo-rest-api -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=6ZWEg9yWkbERGGJK0ju0AKaqgTn7S0wI -e KEYCLOAK_AUTH_SERVER_URL=http://keycloak24:8080 -e KEYCLOAK_REALM=Tunisys user-management-service